apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: boxone
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: boxtow			  ##add this line with correct indentataion to create new pod with diff image 
    image: redis:latest
